#apiVersion: v1
#kind: PersistentVolume
#metadata:
  #name: mongodb-pv
#spec:
  #capacity:
    #storage: 2Gi
  #accessModes:
    #- ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  #hostPath:
    #path: /data/mongodb
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-004e7ffe6995307c5  # <-- YOUR EBS VOLUME ID

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mongodb-pv
---
# =========================================
# MongoDB Secret
# =========================================
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  username: admin
  password: Admin@123
---
# =========================================
# MongoDB Deployment
# =========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7

          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
# =========================================
# MongoDB Service
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
# =========================================
# Backend Deployment
# =========================================
# =========================================
# Backend Deployment
# =========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: yashwantlohar/tws-backend:latest

          ports:
            - containerPort: 3500

          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-service:27017/mydatabase?authSource=admin

            - name: USE_DB_AUTH
              value: "true"

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
---
# =========================================
# Backend Service
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 3500
      targetPort: 3500
      nodePort: 30350
---
# =========================================
# Frontend Deployment
# =========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: yashwantlohar/tws-frontend:latest

          ports:
            - containerPort: 80

          env:
            - name: REACT_APP_API_URL
              value: http://backend-service:3500
---
# =========================================
# Frontend Service
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service

spec:
  selector:
    app: frontend

  type: LoadBalancer

  ports:
    - port: 80
      targetPort: 80
      
